apiVersion: v1
kind: ServiceAccount
metadata:
  name: election
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: election
rules:
  - resources:
      - leases
    apiGroups:
      - coordination.k8s.io
    verbs:
      - create
      - delete
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: election
subjects:
  - kind: ServiceAccount
    name: election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: election
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: election
  template:
    metadata:
      labels:
        app: election
    spec:
      containers:
        - name: main
          image: fill_it
          imagePullPolicy: Always
      serviceAccountName: election
